name: firebase_ml_vision
description: Flutter plugin for Firebase machine learning vision services.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision
version: 0.11.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  firebase_core: ^1.0.2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasemlvision
        pluginClass: FirebaseMlVisionPlugin
      ios:
        pluginClass: FLTFirebaseMlVisionPlugin
