name: firebase_storage_web
description: The web implementation of firebase_storage
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  async: ^2.5.0
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.2
  firebase_storage_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_core_platform_interface: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseStorageWeb
        fileName: firebase_storage_web.dart
