name: firebase_messaging_platform_interface
description: A common platform interface for the firebase_messaging plugin.
version: 1.0.0-dev.10
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_platform_interface

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  firebase_core: ^0.7.0
  plugin_platform_interface: ^1.0.0

dev_dependencies:
  firebase_core_platform_interface: ^2.0.0
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5 <2.0.0"
