name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_functions:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
