name: cloud_functions
description: A Flutter plugin allowing you to use Firebase Cloud Functions.
version: 0.9.0
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.functions
        pluginClass: FlutterFirebaseFunctionsPlugin
      ios:
        pluginClass: FLTFirebaseFunctionsPlugin
      macos:
        pluginClass: FLTFirebaseFunctionsPlugin
      web:
        default_package: cloud_functions_web

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_core_platform_interface: ^3.0.1
  cloud_functions_platform_interface: ^4.0.1
  cloud_functions_web: ^3.1.3
dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.2

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
