name: firebase_analytics_web
description: The web implementation of firebase_analytics
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_web
version: 0.3.0-dev.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'

dependencies:
  firebase: ^9.0.1
  firebase_analytics_platform_interface: ^2.0.0-dev.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAnalyticsWeb
        fileName: firebase_analytics_web.dart
